name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Test Default
        run: cargo test --release -- --nocapture

      - name: Test Session Feature
        run: cargo test --features "session" --release -- --nocapture